### ISSUE TITLE
Minor grammar error on home page

### ISSUE THREAD

**Issue by d3zd3z** [zephyrproject-rtos/infrastructure-old#1]
The [homepage](https://www.zephyrproject.org/) contains a minor grammar error right at the beginning, with the first section title: "What is Zephyr Project". This should be "What is the Zephyr Project".

Grammatically, the phrase "Zephyr Project" is an adjective "Zephyr" modifying the noun "Project". "Project" is countable, and distinguishable (there are other projects), and therefore needs an article. The phrase being a proper noun itself doesn't affect how it is used grammatically.

This can be given low priority.

**Comment by nashif** [comment]
@dbkinder can you please take a look?

**Comment by nashif** [comment]
should be fixed already
