### ISSUE TITLE
Zephyr Website refresh grooming test issue

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#135]
As of 11/14/2019 the new Zephyr website update is being staged. As soon as it is visible we need it to be groomed for anything that is out of date, missing, or things that simply need to be removed.

The intent is to use the Zephyr/Infrastructure GitHub repository to collect these issues and track them.

This issue is intended as a placeholder test issue to determine who gets notification and has the appropriate permissions to deal with them.

**Comment by nashif** [comment]
test

**Comment by mimeriza** [comment]
For test only
