### ISSUE TITLE
Zephyr website - update members page per LF

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#136]
"Just spotted another issue that needs to be fixed before the site goes live.
Please remove Linino from the members page (Silver member).   
They are no longer with the project.   Our current site has been updated
to reflect this, so would prefer to avoid a regression here."

**Comment by galak** [comment]
> "Just spotted another issue that needs to be fixed before the site goes live.
> Please remove Linino from the members page (Silver member).
> They are no longer with the project. Our current site has been updated
> to reflect this, so would prefer to avoid a regression here."

Did you mean Linaro?  Linaro is still a member as far as I know.

**Comment by mimeriza** [comment]
That was an e-mail from Kate. Perhaps they are no longer a sliver member? I'll double check with Kate.
