### ISSUE TITLE
Zephyr Website absolute links will break on site launch

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#142]
There are absolute rather than relative links

**Comment by mimeriza** [comment]
Reported by Lindsay as having been addressed.

Close when verified on live site.

**Comment by dbkinder** [comment]
@mimeriza  Need MCG to verify on the live site as part of the launch testing, but I suspect there will be some absolute links to dev-zephyr-mcg.pantheonsite.io to be found, such as on the 404 error page (``<a href="https://dev-zephyr-mcg.pantheonsite.io" class="tt_button">Back to homepage</a>``) and the image ``src=`` references. I also still see the Videos and Partners pulldown menu items (in the header) are links containing https://dev-zephyr-mcg.pantheonsite.io, which will be incorrect unless changed as the others were, before launch.

I'm not familiar enough with how moving WP sites deals with media references and such.  Maybe it's all magically handled :)  Bottom line, after the move to zephyrproject.org, there must be no references to ``dev-zephyr-mcg.pantheonsite.io`` anywhere.  It won't be visually obvious unless the dev site is temporarily blocked after launch.

**Comment by dbkinder** [comment]
@mimeriza BTW, this should be marked as a blocker, or at least part of the immediate review process after launching the new site.

**Comment by dbkinder** [comment]
As of Dec 10, I still see some links in the header navigation that should be relative.  These will break if not fixed before the site launch, for example:
```
<a title="Videos" href="https://dev-zephyr-mcg.pantheonsite.io/videos/">Videos</a></li>
```

**Comment by Lloveday** [comment]
The remaining links you see in the navigation, are the ones that wordpress changes automatically at launch. They can not be changed to relative manually or the dev site will break. I will also do a search and replace immediately after launch.

**Comment by dbkinder** [comment]
OK, but it's curious that the other links on that menu are relative:
```
<a title="Tools" href="/developer-resources/#developer-tools">Tools</a>
```

**Comment by Lloveday** [comment]
Some of the menu links are wordpress generated. Those will be the ones that are still absolute. The remaining links that contain anchor tags are the ones I have to add in manually because wordpress is not able to automatically generate them.

**Comment by mimeriza** [comment]
These are the links WordPress changes automatically.

**Comment by mimeriza** [comment]
OK. I’ve closed that one as well.

**Comment by dbkinder** [comment]
There must not be any references to ``dev-zephyr-mcg`` anywhere on the new site.  When I do a view-source on the home page I see three.

**Comment by mimeriza** [comment]
My understanding is that WordPress itself will convert these. But we'll check as a priority once the website is launched. It won't immediately cause problems even as long as the staging site is still valid, even if they get left in.

**Comment by dbkinder** [comment]
It did not convert by itself, or they would be correct on the newly launched site.

**Comment by Lloveday** [comment]
I checked on my end and did not see anymore. David please let me know if you see one I'm missing.

**Comment by Lloveday** [comment]
Also, a quick note: if you see any that have "script" before it, those have to stay exactly as is.

**Comment by mimeriza** [comment]
David to verify that his concerns have been addressed.

**Comment by dbkinder** [comment]
I don't see any references to dev-zephyr, so this can remain closed for now.
