### ISSUE TITLE
Zephyr Website: enable the Ecosystem Partners page

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#143]
Need to populate and enable the Ecosystem Partners page.

**Comment by mimeriza** [comment]
See Google Doc for proposed text & layout: https://docs.google.com/document/d/11aGAMGdPGt52pRUcTeZGroxOc6dCFeUV2f4EMZrjkmA/edit?ts=5ddc4fa7

-------------------------------------
Zephyr Preferred Partners
 
The following companies have demonstrated their commitment to the Zephyr project by becoming supporting members and can provide expert services that support rapid development of Zephyr based products.

Company/ contact | Description | Professional Services | Board Support | Other
-- | -- | -- | -- | --
Adafruit<  > |   |   |   |  
Antmicro< > |   |   |   |  
Foundries.io< > |   |   |   |  
Linaro< > |   |   |   |  
SiFive< > |   |   |   |  

* This list is still under construction
 
There are also other companies that support developement of products with Zephyr, and we’re working on building up a list of them.   If your company is interested in being listed, please fill out the following form. 
 
 
----------------------------------------------------------
 
To be added later
 
Zephyr Ecosystem
 
The following consultants have been not reviewed and qualified by the project,  they are listed upon request of the company. 
 
 
Name
Contact link
Company Description
Please select the services you provide
Professional Services
Board Support 
Training
Other  _--- please add.
 
 
Date Listed: 
 
Please note,  this information will be listed on Zephyr’s page for 6 months, and will be automatically deleted after that,  you will need to resubmit this form to continue listing. 
 
 
[Zephyr - Preferred Ecosystem Partners.docx](https://github.com/zephyrproject-rtos/infrastructure/files/3889148/Zephyr.-.Preferred.Ecosystem.Partners.docx)

**Comment by Lloveday** [comment]
Please check the new page and let me know if I am missing any information. Also, please let me know what form fields you would like me to add.

**Comment by dbkinder** [comment]
I'm being captain obvious here, but there's no information about the preferred partners on this page, other than their names. Is this OK for launching?

**Comment by mimeriza** [comment]
The ecosystems partner page is still selectible.

**Comment by Lloveday** [comment]
This page is now turned off

**Comment by mimeriza** [comment]
Recheck with live website
