### ISSUE TITLE
Zephyr Website change tab "Developer Resources" to just "Resources"

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#144]
From Kate: Since we are shifting focus from being primarily developer oriented to being more adoption oriented we should broaden the scope of the resources page and change the label to "Resources".

**Comment by kestewart** [comment]
Also,  please update all references to developer resources.

**Comment by Lloveday** [comment]
This is complete

**Comment by kestewart** [comment]
Reviewed,  and agree its completed.    Thanks!  :-)

**Comment by mimeriza** [comment]
Recheck with live website
