### ISSUE TITLE
Zephyr Website sync the list of media in "Connect" with what is displayed in the footer.

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#145]
The "Connect" media should match what is displayed in the footer. Specifically what is in "Connect" + FB and LinkedIn should be in both places.

**Comment by dbkinder** [comment]
See #164 for more details and locations that should be consistent.

**Comment by Lloveday** [comment]
This has been completed

**Comment by mimeriza** [comment]
Recheck with live website
