### ISSUE TITLE
Zephy website: remove (or justify) use of Facebook SDK

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#152]
Site is loading a facebook SDK for JavaScript. Remove or verify that it’s really necessary.  Documentation for the Facebook SDK says it enables you to use a Like Button and other Social Plugins, but it seems unnecessary for our site since I don’t see a “like button” on the new site’s pages?

**Comment by Lloveday** [comment]
This is needed to allow blogs to be shared on social platforms
