### ISSUE TITLE
Zephyr website: Unexpected console errors

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#153]
JavaScript references to scripts from sharethis.com and facebook.com are throwing errors as noticed in the browser console:

![image](https://user-images.githubusercontent.com/11063618/69576944-2b9b8900-0f82-11ea-84e0-90fa0f82b1de.png)

**Comment by Lloveday** [comment]
This has been resolved

**Comment by mimeriza** [comment]
Not observed on live site
