### ISSUE TITLE
Google Analytics data for new site not showing up

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#154]
Google Tag Manager code is missing from the new site.  Without it, we'll lose our website usage tracking.  (See existing zephyrproject.org site for appropriate code (id=GTM-KMP8MS).

**Comment by Lloveday** [comment]
This is complete

**Comment by mimeriza** [comment]
Recheck with live website

**Comment by dbkinder** [comment]
The Google Tag Manager tracking code is not set up correctly, compared with what's on the previous zephyrproject.org site.  Looks like only a part of the GTM code was added to the pages.  It's missing stuff early on the page like:
```
<!-- Google Tag Manager for WordPress by gtm4wp.com -->
 <script data-cfasync="false" data-pagespeed-no-defer type="text/javascript">//<![CDATA[
   var gtm4wp_datalayer_name = "dataLayer";
   var dataLayer = dataLayer \|\| [];
   //]]>
 </script>
<!-- End Google Tag Manager for WordPress by gtm4wp.com -->
```

And this further down the page:
```
<!-- Google Tag Manager for WordPress by gtm4wp.com -->
  <script data-cfasync="false" data-pagespeed-no-defer type="text/javascript">//<![CDATA[
   var dataLayer_content = [];
   dataLayer.push( dataLayer_content );//]]>
  </script>
  <script data-cfasync="false">//<![CDATA[
   (function(w,d,s,l,i){w[l]=w[l]\|\|[];w[l].push({'gtm.start':
   new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
   j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
   '//www.googletagmanager.com/gtm.'+'js?id='+i+dl;f.parentNode.insertBefore(j,f);
   })(window,document,'script','dataLayer','GTM-KMP8MS');//]]>
   </script>
<!-- End Google Tag Manager -->
<!-- End Google Tag Manager for WordPress by gtm4wp.com -->
```

Results are that I'm not seeing any tracking information in the analytics site since the new site's launch, so there's something amiss.

**Comment by Lloveday** [comment]
I have added the above code to the new site. Please let me know if that didn't fix the issue.

**Comment by dbkinder** [comment]
@Lloveday The cut from chrome and paste into this issue introduced some funny characters and syntax errors in what got put into the new site.  Please pull the correct code from the original zephyrproject.org site.

![image](https://user-images.githubusercontent.com/11063618/71215303-363cfb80-226c-11ea-8042-3fccd6db8aae.png)

**Comment by Lloveday** [comment]
This issue was fixed before the Christmas break. David, please let me know if it is still not working correctly. Thanks.

**Comment by dbkinder** [comment]
Google Analytics data appears to be collecting now, Thanks.
