### ISSUE TITLE
Zephyr website: Use of centered text for paragraphs?

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#155]
I find centered text paragraphs very hard to read (vs. left-justified text). So the body text of, for example, https://dev-zephyr-mcg.pantheonsite.io/learn-about/ is bothersome:

![image](https://user-images.githubusercontent.com/11063618/69577289-edeb3000-0f82-11ea-9cc1-27c9758bffbc.png)

vs. a left-justified version of this text where all the lines start at a consistent place:

![image](https://user-images.githubusercontent.com/11063618/69577347-03605a00-0f83-11ea-85de-d0561c6c9622.png)

**Comment by bprestonlf** [comment]
Marketing Committee discussed on July 21, 2020. Decision to leave site as is -- center aligned.
