### ISSUE TITLE
Zephyr website: header style inconsistent across site

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#156]
On the Community/Blog page (https://dev-zephyr-mcg.pantheonsite.io/community/#blog) I clicked on the first items Read more link and got this page.  (Notice the blue background for the header is missing):

![image](https://user-images.githubusercontent.com/11063618/69577900-3820e100-0f84-11ea-91db-740cb2933f34.png)

**Comment by dbkinder** [comment]
This is still a problem on the newly launched site

**Comment by Lloveday** [comment]
The chosen theme design does not have a header on the blog page.

**Comment by bprestonlf** [comment]
Marketing Committee 6/23/20 - Not doing.
