### ISSUE TITLE
Zephyr website: "Download logo" link seems out of place

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#163]
The "Download Logo" link seems out of place as a sentence in the "Community Tools" column of the how to contribute section:

![image](https://user-images.githubusercontent.com/11063618/69582380-5808d280-0f8d-11ea-9764-d543c8cea3c0.png)

The "email us" should be a mailto: link where ever this sentence ends up.

**Comment by mimeriza** [comment]
Duplicated in issue #198
