### ISSUE TITLE
Zephyr website: Make community tools/connect/social media lists consistent

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#164]
We've got different lists scattered around of how to be part of the community, and they're all different:

On https://dev-zephyr-mcg.pantheonsite.io/developer-resources/#how-to-contribute

![image](https://user-images.githubusercontent.com/11063618/69582622-d2395700-0f8d-11ea-8fd4-a365b6a3c0e0.png)

On https://dev-zephyr-mcg.pantheonsite.io/community/#connect

![image](https://user-images.githubusercontent.com/11063618/69582679-f432d980-0f8d-11ea-90bf-78c3f0b6df6b.png)

In the footer:

![image](https://user-images.githubusercontent.com/11063618/69582707-057be600-0f8e-11ea-9278-88407baa761a.png)

In the header menu pull-down list:

![image](https://user-images.githubusercontent.com/11063618/69582855-568bda00-0f8e-11ea-89d7-d9a7e8305c8f.png)

In the Contact Us page (https://dev-zephyr-mcg.pantheonsite.io/contact-us/):

![image](https://user-images.githubusercontent.com/11063618/69584790-e764b480-0f92-11ea-8b9c-ae70f2487ddc.png)

**Comment by dbkinder** [comment]
(matching priority of this issue with previously prioritized #145)

**Comment by Lloveday** [comment]
This has been completed

**Comment by mimeriza** [comment]
Revisit the "how to contribute" page and make sure that's what we want. But not a blocker.

**Comment by mimeriza** [comment]
Community tools is missing YouTube & Twitter

**Comment by mimeriza** [comment]
Fixed in live site
