### ISSUE TITLE
Zephyr Website: Image for Zephyr besides "About Zephyr Project" chopped weird. 

### ISSUE THREAD

**Issue by kestewart** [zephyrproject-rtos/infrastructure-old#167]
See: 
![Screen Shot 2019-11-25 at 4 52 36 PM](https://user-images.githubusercontent.com/13152682/69585117-69a9a480-0fa4-11ea-84ee-4cd54c4f8965.png)

**Comment by kestewart** [comment]
please add blocker label.

**Comment by mimeriza** [comment]
Also on the demo's page. Check for other instances as well.

**Comment by Lloveday** [comment]
These have been adjusted to the best of my ability. Please let me know if they look ok on your end.

**Comment by mimeriza** [comment]
Prefer black text on white background. May want to find a better image.

**Comment by mimeriza** [comment]
Previous comment is with regard to the Zephyr Logo on the "About Zephyr" page (and maybe another)

**Comment by Lloveday** [comment]
I am not able to access the folder you sent containing your logos. can you please send over the new image you would like me to use? Thanks.

**Comment by Lloveday** [comment]
I have added the new image. Please let me know if it looks ok on your end.

**Comment by mimeriza** [comment]
Fixed in live site
