### ISSUE TITLE
Zephyr website: Project member-specific pages

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#168]
The Project Members page ( https://dev-zephyr-mcg.pantheonsite.io/project-members/ ) has logos for members, but no further information about their involvement and participation in the project.  

Maybe the TSC voting members/marketing committee can provide a blurb about what their company is contributing to the project. 

Just making the logos link to the company website homepage wouldn't be useful.

Also, this page lists three project membership levels, but four are listed in the table on the https://dev-zephyr-mcg.pantheonsite.io/become-a-member/ page.

**Comment by kestewart** [comment]
Please add web links to company home pages.    Kate & Brett to work with Lindsay for links.

**Comment by bprestonlf** [comment]
Updated URL: https://www.zephyrproject.org/project-members/

1. Intel = https://www.intel.com/
2. Nordic = https://www.nordicsemi.com/
3. NXP = https://www.nxp.com/
4. Oticon = https://www.oticon.com/
5. Adafruit = https://www.adafruit.com/
6. Antmicro = https://antmicro.com/
7. Bose = https://www.bose.com/
8. Foundries = https://foundries.io/
9. Linaro = https://www.linaro.org/
10. SiFive = https://www.sifive.com/
11. Synopsys = https://www.synopsys.com/
12. Texas Instruments = https://www.ti.com/
13. Beijing University of Posts and Telecommunications = https://english.bupt.edu.cn/
14. Eclipse Foundation = https://www.eclipse.org/org/foundation/
15. ICCS = https://www.iccs.gr/en/institute-of-communication-and-computer-systems/
16. Northeastern University = https://www.northeastern.edu/
17. Vancouver Hack Space = http://vanhack.ca/wp/

**Comment by Lloveday** [comment]
The links have been added to the site.
