### ISSUE TITLE
Zephyr website: syntax errors found on home page

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#172]
- On the home page, w3c validator is complaining about a style specified without the required semicolon after each attribute (see lines 947-950).  This may cause some style attributes to be ignored.

```

style="z-index:9;font-family:Roboto;text-transform:uppercase;text-shadow:0 10px 20px rgba(0, 0, 0, 0.2)
color:white
font-size:70px
font-weight:900
text-transform:uppercase;"
```

- The LF logo at the top of the page specifies an image height="20px" but should be just "20" in HTML5.

- On line 1304 in the source for the home page, there's this div with a syntax error:
```
<div class="vc_gitem-animated-block " ">
```

- On line 1305 there's a closing ``</p>`` without an opening ``<p>``, and there's an error later on the line with an erroneous "a" attribute on an anchor tag:
```
<a class="vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-rounded vc_btn3-style-flat vc_btn3-color-juicy-pink" a href=".....
```

Similar problems are found on line 306, 311, and 312

You might want to do some validation checks on the HTML...

**Comment by mimeriza** [comment]
Will probably be fixed with the next WP update. Is invisible to users.

**Comment by dbkinder** [comment]
Unclear when the next WP update will happen.  Need to investigate if this problem is WordPress, Theme, or a coding error in the implementation of the site.
