### ISSUE TITLE
Zephyr website: Need a "Press Release" area under "Community"

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#175]
As reported by Maemalynn Meanor, "there currently isn’t a press release section. Please add this under "Community" so that our press releases could be easily found.

**Comment by kestewart** [comment]
Please make this a blocker.

**Comment by Lloveday** [comment]
I just wanted to be sure we noted that Press releases are under announcements. We can easily change this if needed.

**Comment by Lloveday** [comment]
This has been checked and approved by Mae.
