### ISSUE TITLE
Zephyr website: php warnings occasionally printed out when viewing pages

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#178]
A PHP warning message is showing occasionally when displaying the home page.  (I have also seen it occasionally on other pages, too.)

![image](https://user-images.githubusercontent.com/11063618/69678890-ae444700-105b-11ea-92af-3e3825a96909.png)

This appears to be an incompatibility introduced by PHP v7.3, and looks like it's coming from an incompatible plugin: ``plugins/incubator-framework/ReduxCore/extensions/customizer/extension_customizer.php``  (as noticed by others: https://forums.envato.com/t/problemes-with-incubator-framework/266478).  Some have eliminated the error by downgrading PHP to v7.2, but that likely has consequences too.

**Comment by mimeriza** [comment]
Not observed in live site.
