### ISSUE TITLE
Zephyr website: Blog page comments

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#179]
Reported by Mae and Ebba, "Blog - the blog on the far left is not the same size as the others, looks a bit odd." The blog article summary boxes being displayed on the blog page aren't similar-sized (the one on the left is much longer).

![image](https://user-images.githubusercontent.com/11063618/69680783-d1252a00-1060-11ea-9e14-b4a6366a8036.png)

Also, the "Load more" button doesn't look like all the other buttons on the site:

![image](https://user-images.githubusercontent.com/11063618/69681001-85bf4b80-1061-11ea-8346-d645ee06c575.png)  
![image](https://user-images.githubusercontent.com/11063618/69681011-91ab0d80-1061-11ea-97d9-fe3872185862.png) 
![image](https://user-images.githubusercontent.com/11063618/69681062-b43d2680-1061-11ea-86d1-198dc6057841.png) 
![image](https://user-images.githubusercontent.com/11063618/69681071-bdc68e80-1061-11ea-8bd1-ea5dcf37a440.png)

**Comment by kestewart** [comment]
There was other feedback as well,  in that a request for displaying most recent first,  and having date of post included.

**Comment by Lloveday** [comment]
The button design has been fixed. The box sizing issue is not something I can adjust. This is default for the theme and the boxes auto resize based on title length. In order for them to be the same size, the titles will need to all be the same length of characters.

**Comment by mimeriza** [comment]
Some way to visually differentiate blogs from events in display.

**Comment by mimeriza** [comment]
This is buried in the template and impossible to fix.
