### ISSUE TITLE
Zephyr Website: Home page video should play on website rather than YouTube

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#180]
Per Ebba: Video - Ideally this would play on the website and not open on youtube.

**Comment by dbkinder** [comment]
On the home page we see an href with target="_blank", which will play the video on a new tab:
```
<a href="https://www.youtube.com/watch?v=JEpY_ETJ_jE" target="_blank">
```
but we could do what's on the Videos page (https://dev-zephyr-mcg.pantheonsite.io/videos/), where we're playing the video in an iframe on the page :
```
<iframe id="_ytid_27490" class="__youtube_prefs__ iframe-embed" title="YouTube player" src="https://www.youtube.com/embed/R0GCLJRCYW0?enablejsapi=1&amp;autoplay=0&amp;cc_load_policy=0&amp;iv_load_policy=1&amp;loop=0&amp;modestbranding=0&amp;rel=1&amp;fs=1&amp;playsinline=0&amp;autohide=2&amp;theme=dark&amp;color=red&amp;controls=1&amp;" allowfullscreen="allowfullscreen" data-origwidth="1080" data-origheight="608" data-no-lazy="1" data-skipgform_ajax_framebjll="" data-aspectratio="0.608" data-mce-fragment="1"></iframe>
```

**Comment by bprestonlf** [comment]
6/23/20 Marketing Committee - Theme does not support video playing on the actual site. Lindsay will review a few more options before closing the request.

**Comment by Lloveday** [comment]
A new WordPress update allowed for us to get this resolved
