### ISSUE TITLE
"Learn" link in the header is not clickable, all others are

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#185]
The header has navigation choices that are all clickable, except for "Learn":
![image](https://user-images.githubusercontent.com/11063618/69742101-0c6f3980-10f1-11ea-8680-9e26b5551112.png)

The "Vision" choice on the submenu actually takes you to the "Learn" page, but not to the "vision" section of that page. To be consistent on the header, clicking on "Learn" should take you to the "Learn" page.

**Comment by Lloveday** [comment]
This is complete

**Comment by dbkinder** [comment]
@Lloveday Thanks. Alas, unless I missed it previously, the "Members" name in the header was clickable last week,, but now it's not.

That's weird.  Unless you just fixed this, the "Members" name is clickable now. Nevermind.

**Comment by mimeriza** [comment]
Recheck with live website
