### ISSUE TITLE
Zephyr Website: Transfer newly added events

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#186]
Per Mae: I just added added two confirmed events to the Zephyr website - Embedded World and a keynote for Kate. Can you please make sure the website team transfers this to the new website?

https://www.zephyrproject.org/events/

**Comment by Lloveday** [comment]
This is complete

**Comment by mimeriza** [comment]
Looks like keynote for Kate is still missing

**Comment by Lloveday** [comment]
This is the one I added that mentions Keynote. Is this correct or am I missing one? https://dev-zephyr-mcg.pantheonsite.io/ospert-2020-workshop-at-ecrts-july-7-2020/

**Comment by mimeriza** [comment]
OK, great! I’ll close that one.

**Comment by mimeriza** [comment]
Has been added: pointer to https://dev-zephyr-mcg.pantheonsite.io/ospert-2020-workshop-at-ecrts-july-7-2020/

**Comment by mimeriza** [comment]
Date on new item needs to be hidden - per Mae

**Comment by Lloveday** [comment]
event item dates have been turned off

**Comment by mimeriza** [comment]
Mae to confirm that this is what she needed.

**Comment by mimeriza** [comment]
Mae confirmed.
