### ISSUE TITLE
Zephyr Website: Blog display

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#188]
From Mae:
Thanks for the updates. I think we’re close but there might be a bit more work needed on the community section. It looks like all of the blogs and coverage were copied over from the old website  (thank you!) but it’s a little confusing because they’re all bunched together. For example - here’s screenshot - the first three boxes are blogs. The fourth one is coverage from last year. Is there a way we can separate the coverage from the blogs and make the boxes standout more? Maybe add the dateline back into the blog preview and add images so it’s not all just content? I believe most of those blogs have images we can spike out or include as the feature image.

**Comment by mimeriza** [comment]
Needs dates and block size is inconsistent.

**Comment by Lloveday** [comment]
The dates have been added to the posts previews.

**Comment by mimeriza** [comment]
Recheck with live website - may be duplicate issue
