### ISSUE TITLE
Zephyr Website: Missing Announcements section

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#189]
From Mae:
Also, there still isn’t an Announcement section. Under community, can you please add in Announcements (you can find the press releases to add here https://www.zephyrproject.org/news/announcements/  and an In the News tab where you can feature the coverage?

**Comment by Lloveday** [comment]
The announcements section has been added.

**Comment by mimeriza** [comment]
Make sure there is a date with each of the items.

**Comment by mimeriza** [comment]
Recheck with live website
