### ISSUE TITLE
Zephyr Website: Community Guidelines should be recombined into a single tab

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#191]
In the original the Community Guidelines was one section. This has been split into two sections. This should be recombined. 

The "Read Before Contributing" should be a title followed by the "Important:..." text. And move it to before the overview bullets.

**Comment by Lloveday** [comment]
This is complete

**Comment by mimeriza** [comment]
Recheck with live website
