### ISSUE TITLE
Zephyr Website: Resources --> Presentations

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#197]
First it hides the title "Presentations" so that you can't tell where you went. This is a problem with other navigation.

Second: Sync with Mae on what should go in the Presentations page - Gold Deck is old etc.
Have 4-5 from last year and add links to videos etc.

Long term sync with board on what needs to be highlighted.

**Comment by dbkinder** [comment]
The "Presentations" heading being hidden is a site-wide issue reported as issue #150 (Zephyr Website navigation links offset)

**Comment by mimeriza** [comment]
From Mae:
I looked over the Gold Deck yesterday and I think it’s in a good spot. There are a few things Kate and Megan have to clean up but I think we can PDF it and post it on the presentations page. 

Other than that, I think the videos and presentations of our members speaking at events could be added here. For example, the ones we just added for OSS/ELC EU. Does that help or did you have something else in mind?

**Comment by mimeriza** [comment]
Links to desired content per Mae:
Here are the ones currently on the site: https://www.zephyrproject.org/project-resources/videos/

Megan added the ELC EU videos to youtube a few weeks ago but they haven’t made their way on to the current site yet. Here’s the link to the list on youtube: https://www.youtube.com/watch?v=39TUXBOS15Y&list=PLzRQULb6-ipHBFB20omgW1_-kED5y51j7

**Comment by Lloveday** [comment]
The issues with the titles being cut off have now been resolved.

**Comment by Lloveday** [comment]
I have added a link to the "Zephyr Project Technical Talks" playlist under the "presentations" section.

**Comment by mimeriza** [comment]
Recheck with live website
