### ISSUE TITLE
Zephyr Website: Download Logo is strange and missing e-mail link

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#198]
Text wraps well short of the line length which looks odd. Probably because it is lining up with the column above it.
Also the "e-mail us" should provide an e-mail link.

**Comment by dbkinder** [comment]
See previously reported issue #163

**Comment by Lloveday** [comment]
I have moved the "download logo" section down to separate it from community tools and centered the text on its own line. The email link was also added.
![Screen Shot 2019-12-05 at 1 50 16 PM](https://user-images.githubusercontent.com/58404865/70264552-a2950680-1766-11ea-98dd-429d936dd0cc.png)

**Comment by mimeriza** [comment]
Recheck with live website
