### ISSUE TITLE
images referenced by blog/articles are missing

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#201]
On the newly launched site, many if not all images referenced by blog/articles are missing

For example, https://www.zephyrproject.org/zephyr-project-f2f-meeting-of-the-minds/
Is throwing three 404 errors for missing images referenced in the article:
 

- GET https://www.zephyrproject.org/wp-content/uploads/sites/38/2019/05/Zephyr-TSC-PDX-0012-190424-1024x683.jpg 404
- GET https://www.zephyrproject.org/wp-content/uploads/sites/38/2019/05/IMG_2536-1024x768.jpg 404
- GET https://www.zephyrproject.org/wp-content/uploads/sites/38/2019/05/Zephyr-TSC-PDX-0005-190424-1-1024x683.jpg 404
 
And https://www.zephyrproject.org/getting-started-with-zephyr-rtos-on-nordic-nrf52832-hackable/  has 23 missing images.

**Comment by Lloveday** [comment]
complete

**Comment by mimeriza** [comment]
I scanned back through all of them and seemed to see images where expected and got no 404's.

**Comment by mimeriza** [comment]
I can confirm that most of the photos have been added back to the blogs. One particular blog - Amy’s presentation recap - is still missing a photo. I think it was a photo of her presenting. Please add that back in and we can then close out 201. 

I don’t believe I have GA access to the new site, so I can’t check it. David will have to do it when he’s back in the office. 

Thanks,
Mae
