### ISSUE TITLE
Contact form email destination needs updating

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#204]
The contact form email address is set to info@morriscreative.com and should be info@zephyrproject.org (unless MCG is going to handle all emails about the project and site).  

Similarly on the settings page, the email address is also set to info@morriscreative.com.

The WordPress admin page is complaining that the "from" address on this form has a problem:
![image](https://user-images.githubusercontent.com/11063618/71105700-d878b880-2172-11ea-88c4-091d567e9f45.png)

**Comment by Lloveday** [comment]
this has been resolved

**Comment by mimeriza** [comment]
Verified

**Comment by dbkinder** [comment]
@mimeriza Did you try sending an email via this form to verify it was received?
