### ISSUE TITLE
Zephyr Website: Display on Chrome small fonts

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#207]
Reported by a TSC member. Sometimes, using Chrome, he sees the fonts at the top of the screen as very small. Other members using Chrome did not demonstrate the same issue. Nor did it happen for the reporter using other browsers. All report having the latest version of Chrome. Hopefully a more detailed report will be submitted.

**Comment by dbkinder** [comment]
@carlescufi Can you provide a screenshot and Chrome version number you're using (on Windows 10, right)?  And can you verify you're running Chrome at 100% browser size.

**Comment by carlescufi** [comment]
Sure, here is the screenshot, taken with Chrome Version 79.0.3945.88 (Official Build) (64-bit):

![image](https://user-images.githubusercontent.com/12450381/71187307-1fec6b00-227f-11ea-8ed8-5f6f40bef380.png)

**Comment by bprestonlf** [comment]
Marketing Committee 6/23/20: No other users able to replicate. Good to close issue.
