### ISSUE TITLE
Unexpected CSS style on blog headings

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#209]
Wandering through some of the migrated blog posts, I'm finding the style for headings is unexpected.  For example in [Co-simulating HDL models in Renode with Verilator running on Zephyr RTOS](https://www.zephyrproject.org/4117-2/) the title (h1) is smaller than a subheading (h3):

![image](https://user-images.githubusercontent.com/11063618/71122045-8c3e7000-2194-11ea-9c23-df136018f8b5.png)

And in this blog (https://www.zephyrproject.org/zephyr-an-operating-system-for-iot/) it looks like the author (incorrectly) used h1 and h2 headings within the document, and they look really odd:

![image](https://user-images.githubusercontent.com/11063618/71122348-361dfc80-2195-11ea-8b2f-6e7a5418a827.png)

**Comment by Lloveday** [comment]
The blog title font sizes are now larger. As for the inconsistent headings within the blogs, when the blogs were migrated, the styling was copied over exactly how it was on the old site. To fix this, edit the blog post and change the headings to h3 or h4 accordingly. I would be happy to go through them all and check for this, but we will need to put together a time estimate for that.

**Comment by mimeriza** [comment]
Will close this as something we can fix.
