### ISSUE TITLE
Previous/Next links on Blog and Event posts don't stay within their category

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#210]
When I click on a blog or event post, there are previous and next links at the bottom of the page that I would expect to take you to the previous and next blog or the next event post as appropriate within the category I'm viewing.   Instead, these links are taking me to posts in any category.

**Comment by Lloveday** [comment]
This is a set function of the theme. It is set up based on date and includes all categories by default. This is not something that can easily be changed. Several code templates would need to be edited. I suggest we turn those links off in order to prevent confusion.

**Comment by mimeriza** [comment]
Will not fix as it is tied to the operation of the theme.
