### ISSUE TITLE
List of SDK downloads is missing

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#212]
The new website is missing information needed to download Zephyr SDK releases.  The previous site had a downloads section (pictured here: https://www.zephyrproject.org/zephyros-sdk-version-0-9-5-is-now-available/) that does not exist on the new site.  

This was reported as a Zephyr documentation issue: https://github.com/zephyrproject-rtos/zephyr/issues/21706

**Comment by Lloveday** [comment]
This looks to have been resolved on the documentation site.
