### ISSUE TITLE
Add Contact Form to https://www.zephyrproject.org/contact-us/

### ISSUE THREAD

**Issue by bprestonlf** [zephyrproject-rtos/infrastructure-old#217]
Need Agency to help update the form styling, and add to https://www.zephyrproject.org/contact-us/. HTML is below:

------START HTML--------

 

<div id="message"></div>
<form id="myform" action="https://cloud.email.thelinuxfoundation.org/Zephyr-Contact-Us-Submission">
<label for="FirstName">First Name
<input type="text" name="FirstName" required="">
</label><br><br>
<label for="LastName">Last Name
<input type="text" name="LastName" required="">
</label><br><br>
<label for="EmailAddress">Email*
<input type="text" name="EmailAddress" required="">
</label><br><br>
<label for="company">Company
<input type="text" name="company">
</label><br><br>
<label for="comments">Comments
<textarea type="text" name="comments"></textarea>
</label><br><br>

<input type="hidden" id="txtUrl" name="txtUrl" value="" readonly="">
<script>
document.getElementById('txtUrl').value = window.location.href;
</script>

<input style="background-color: #36b0c9; color:#fff" type="submit" value="Submit" id="loginbtn">
</form>
<div id="response"></div>

<script>
(function($) {
$("#myform").on("submit", function(e) {
e.preventDefault();
$.ajax({
url: $(this).attr("action"),
type: 'POST',
data: $(this).serialize(),
beforeSend: function()

{ $("#myform").toggle(); $("#message").html("Thank you for your submission."); }
,
success: function(data)

{ $("#message").hide(); msg = $(data).find("p"); $("#response").html(msg); }
});
});
})(jQuery);
</script>
<script>
jQuery("#loginbtn").click(function()

{ //jQuery("#myform").toggle(); // toggle will show hidden element and vice versa }
);
</script>

**Comment by kestewart** [comment]
@lloveday - ok if we assign this to you?

**Comment by bprestonlf** [comment]
@Lloveday Can you provide a status update for this ticket?

**Comment by Lloveday** [comment]
Hi Brett, My apologies. This should have pushed to the live when I published the other changes last week. I will take a look and see why it isn't showing up ASAP.
