### ISSUE TITLE
Zephyr website: Update Benefits page

### ISSUE THREAD

**Issue by MeganHansen** [zephyrproject-rtos/infrastructure-old#219]
On the benefits page (https://www.zephyrproject.org/benefits/), please: 

1. Update the Security section to: 

- include the following as the third bullet point: "Includes CNA with Product Security Incident Response Team (PSIRT) response team"

- remove the fifth bullet: "long term support" (it's going to appear in a new section, as noted below)

2. Add an entirely new third section (above "Powerful") called "Product Ready", with the following two bullet points: 

- Long term support (LTS) with security updates

- Certification-ready with Auditable 

3. Under "Connected", 

- remove the "star" next to "Wi-Fi*" (since there is no supporting footnote).

- update the last bullet so that it reads "Supports standards like 6LoWPAN, CoAP, IPv4, IPv6, Ethernet, USB, CAN and Thread

**Comment by bprestonlf** [comment]
@MeganHansen - https://www.zephyrproject.org/benefits/ has been updated
