### ISSUE TITLE
Zephyr Website: Project Overview is 2 years old

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/infrastructure-old#223]
On Zephyr website, we can find a link to a project presentation made on 18'03.
Part of the information provided is still accurate (governance model, ...) but some has to be removed or updated (Roadmap, number of boards, ...)

Presentation is very accessible:
https://www.zephyrproject.org/developer-resources/#presentations
https://www.zephyrproject.org/wp-content/uploads/2019/10/Zephyr-Project-Overview-20180316-v2.pdf

**Comment by erwango** [comment]
@bprestonlf I think it would be nice to update the presentation for the time we release v2.3.0

**Comment by kestewart** [comment]
Updated slidedeck sent to your inbox @bprestonlf

**Comment by bprestonlf** [comment]
https://www.zephyrproject.org/developer-resources/#presentations has been updated. Thank you @erwango and @kestewart

**Comment by kestewart** [comment]
@erwango - if the updated version isn't what you're looking for,  please reopen this issue.    I'm closing it for now as the updated slides are available on the website now.

**Comment by erwango** [comment]
It's perfect, txs @kestewart & @bprestonlf  !
