### ISSUE TITLE
buildkite fails if no sanitycheck output was generated

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/infrastructure-old#227]
When submitting PRs that do not trigger sanitycheck (see e.g. https://github.com/zephyrproject-rtos/zephyr/pull/26324 and https://buildkite.com/zephyr/zephyr/builds/995), no `sanitycheck-*.xml` file is produced. This causes buildkite to fail.

**Comment by galak** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/26340

**Comment by henrikbrixandersen** [comment]
Confirmed.
