### ISSUE TITLE
zephyr website: Dead link Members -> Governance -> Admin & Leaders

### ISSUE THREAD

**Issue by chrta** [zephyrproject-rtos/infrastructure-old#228]
When i select Members -> Governance -> Admin & Leaders i get the following dead link:
http://governance/#administration-leaders

![zephyr_dead_link](https://user-images.githubusercontent.com/974411/94482562-c59f1400-01d9-11eb-8085-1caaeeef11dc.png)

Browser Google Chrome 85.0.4183.102 in Ubuntu 18.04

**Comment by bprestonlf** [comment]
@kestewart - This should be fixed now. Please verify it works for you.

**Comment by chrta** [comment]
It is working for me now.

**Comment by bprestonlf** [comment]
Closing ticket. @chrta Thank you for filing the issue!
